CREATE TABLE PERSON (
    ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    AGE NUMBER(3) NOT NULL
);

CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE USERS (
    USERNAME VARCHAR(16) PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    ENABLED NUMBER(1) NOT NULL
);

CREATE TABLE USER_ROLES (
    USERNAME VARCHAR(16) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE OAUTH_TOKENS (
    TOKEN VARCHAR(256) PRIMARY KEY,
    EXPIRES DATE NOT NULL,
    USER_ID VARCHAR(16) NOT NULL,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USERNAME)
);